version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace
    ports:
      - 80:80
    environment:
        PHP_EXTENSION_XDEBUG: 1
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        PHP_EXTENSION_GD: 1
        APACHE_DOCUMENT_ROOT: /workspace/docroot
  db:
    image: percona:5.7.22
    restart: true
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: d9
        MYSQL_USER: d9
        MYSQL_PASSWORD: d9
        MYSQL_ROOT_PASSWORD: d9root

  solr:
    image: solr:7.7
    volumes:
      - ./docker/solr-conf/7.x:/solr-conf/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - tr
      - /solr-conf
    networks:
      - front
    depends_on:
      - app
      - db
    restart: always

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
