version: "3"
services:
  app:
    build: ./docker/php
    volumes:
      - ../:/workspace
    tty: true
    working_dir: /workspace/docroot
    volumes:
      - ./:/workspace

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: percona:5.7.22
    restart: true
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: d9
        MYSQL_USER: d9
        MYSQL_PASSWORD: d9
        MYSQL_ROOT_PASSWORD: d9root

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
