version: "3"
services:
  app:
    build: ./docker/php
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    tty: true
    environment:
        APP_ENV: local
        IMAGE_PHP: skilldlabs/php:81
        PHP_EXTENSION_XDEBUG: 1
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        PHP_EXTENSION_GD: 1
        APACHE_DOCUMENT_ROOT: /workspace/docroot
  db:
    image: percona:5.7.22
    restart: true
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: d9
        MYSQL_USER: d9
        MYSQL_PASSWORD: d9
        MYSQL_ROOT_PASSWORD: d9root

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
